version: '3.8'

services:
  db:
    image: postgres:15
    container_name: busify-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1044
      POSTGRES_DB: busify
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: busify-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/busify
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1044
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  postgres_data: