spring.application.name=Busify

spring.datasource.url=jdbc:postgresql://localhost:5432/busify
spring.datasource.username=postgres
spring.datasource.password=1044
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

application.security.jwt.secret-key=c2VjcmV0LWtleS1kZWZhdWx0LWJ1c2lmeS1wcm9qZWN0LTIwMjYtc3ByaW5nLWJvb3Q=

spring.elasticsearch.uris=http://elasticsearch:9200
spring.elastisearch.connection-timeout=5s

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin123

spring.data.redis.host=redis
spring.data.redis.port=6379
spring.cache.type=redis
spring.cache.redis.time-to-live=300000

springdoc.swagger-ui.urls[0].name=Busify API
springdoc.swagger-ui.urls[0].url=/v3/api-docs
springdoc.swagger-ui.urls-primary-name=Busify API