spring.application.name=Busify

spring.datasource.url=jdbc:postgresql://localhost:5432/busify
spring.datasource.username=postgres
spring.datasource.password=1044
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

application.security.jwt.secret-key=c2VjcmV0LWtleS1kZWZhdWx0LWJ1c2lmeS1wcm9qZWN0LTIwMjYtc3ByaW5nLWJvb3Q=

spring.elasticsearch.uris=http://elasticsearch:9200
spring.elastisearch.connection-timeout=5s

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin123